const mongoose = require('mongoose');

const PlaylistSchema = new mongoose.Schema(
  {
    userId:        { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    name:          { type: String, required: true, trim: true },
    description:   { type: String, default: '' },
    cover:         { type: String, default: '' },        // thumbnail URL
    mood:          { type: String, default: '' },        // auto-tag from emotion
    autoGenerated: { type: Boolean, default: false },    // true = created from face scan
    isPublic:      { type: Boolean, default: false },

    songs: [
      {
        youtubeId: { type: String, required: true },
        title:     { type: String, default: '' },
        artist:    { type: String, default: '' },
        thumbnail: { type: String, default: '' },
        addedAt:   { type: Date, default: Date.now },
      },
    ],
  },
  { timestamps: true }
);

PlaylistSchema.index({ userId: 1 });

module.exports = mongoose.model('Playlist', PlaylistSchema);